- name: Create Playbooks to Configure Systems to a Specified State
  hosts: all
  tags: install_start
  become: yes

  tasks:

  - name: install htop
    package:
     name: htop
     state: latest
    tags: install

  - name: install web
    package:
     name: httpd
     state: latest
    when: ansible_os_family == "RedHat"
    tags:
     - install
     - web
  - name: start webserver
    service:
     name: httpd
     state: started
     enabled: yes
