- hosts: all
  become: yes

  tasks:
    - name: gather hardware
#      get_url:
#        url: http://localhost/files/hardware.empty
#        dest: /root/hardware.txt
      copy:
        src: hardware.empty
        dest: /root/hardware.txt
    - lineinfile:
        path: /root/hardware.txt
        line: ansible_fqdn={{ ansible_fqdn }}
    - lineinfile:
        path: /root/hardware.txt
        line: ansible_hostname={{ ansible_hostname }}
    - lineinfile:
        path: /root/hardware.txt
        line: ansible_devices.sda.size={{ ansible_devices.sda.size }}
