- hosts: all
  become: yes

  vars:
    timesync_ntp_servers:
      - hostname: 172.24.1.1
        iburst: yes

  tasks:
    - name: install rhel-system-roles
      yum:
        name: rhel-system-roles
        state: present

  roles:
    - rhel-system-roles.timesync
