    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: true
    - name: put index.html
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
    - name: enable firewall
      service:
        name: firewalld
        state: started
        enabled: true
    - name: open firewall for http
      firewalld:
        service: http
        immediate: true
        permanent: yes
        state: enabled
