- name: timesync
  hosts: all
  become: yes

  vars:
    timesync_ntp_servers:
      - hostname: 172.24.0.1
        iburst: yes

  roles:
  - { role: rhel-system-roles.timesync, tags: ['timesync', 'ntp'] }
